[package]
name = "bitpacking"
version = "0.1.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["integer", "compression", "bitpacking"]
description = "Fast integer compression/decompression via SIMD bit-packing. Port of simdcomp to rust."

[dependencies]
crunchy = "0.1.6"

[dev-dependencies]
rand = "0.3"

[features]
default = ["sse3"]
sse3 = []
avx2 = []
