[package]
name = "bitpacking"
version = "0.1.0"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["integer", "compression", "bit packing"]

[dependencies]
crunchy = "0.1.6"

[dev-dependencies]
rand = "0.3"
